Allowing JavaEE <-> JakartaEE interoperability scenarios.
wildfly/wildfly-http-client pull request #81
Opened 2022-06-22 19:00 UTC by ropalka

https://issues.redhat.com/browse/WEJBHTTP-79

2022-07-01 15:13 UTC, fl4via commented
@ropalka FYI, I am looking into this, but I want to review all PRs before giving feedback.

2022-07-05 05:12 UTC, fl4via commented
@ropalka have you tried adding the attribute to indicate backwards compatibility to remote-outbound-connection? If I understand correctly, this PR will enable/disable transformation to all invocations instead of doing it per connection

2022-07-05 05:14 UTC, fl4via requested changes
I need to clarify the usage of the new attribute in remote-outbound-connection for this PR and for https://github.com/wildfly/jboss-ejb-client/pull/543

2022-07-05 05:14 UTC, fl4via commented on common/src/main/java/org/wildfly/httpclient/common/MarshallingHelper.java
> + * Copyright 2021 Red Hat, Inc., and individual contributors
there are some clases that are using 2021 instead of 2022 and this needs to be reviewed

2022-07-06 09:52 UTC, ropalka commented
> @ropalka have you tried adding the attribute to indicate backwards compatibility to remote-outbound-connection? If I understand correctly, this PR will enable/disable transformation to all invocations instead of doing it per connection

I didn't. IMHO this is fine to have it this way for EAP Beta release so QA can start testing it. Your proposal about WildFly model will be implemented before final @fl4via .

2022-07-06 09:53 UTC, ropalka commented on common/src/main/java/org/wildfly/httpclient/common/MarshallingHelper.java
> + * Copyright 2021 Red Hat, Inc., and individual contributors
This is because this PR was implemented in November 2021.

2022-07-06 10:02 UTC, ropalka commented on common/src/main/java/org/wildfly/httpclient/common/MarshallingHelper.java
> + * Copyright 2021 Red Hat, Inc., and individual contributors
Fixed

2022-08-15 09:24 UTC, merged